platform :ios do

  lane :upload do
    ipa_path = ENV['IPA_PATH']

    # Ensure IPA path is available
    unless ipa_path
      UI.user_error!("IPA_PATH environment variable is not set. Make sure to run 'development' lane first.")
    end

    # Upload IPA to TestFlight
    upload_to_testflight(
      ipa: ipa_path,
      username: "virendra@emizentech.com",
      apple_id: "6504559316",
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      itc_provider: "55DJQPG6M9"
    )
  end
end

