export const BGImages = {
    SPLASHLOGO: require('../asstes/Images/splash.png'),
    BACKGROUND_LOGO: require('../asstes/Images/backgroundLogo.png'),
    DOWN_ARROW: require('../asstes/Images/down.png'),
    LOGO: require('../asstes/Images/logo.png'),
    PROFILE: require('../asstes/Images/profile.png'),
    CAMERA: require('../asstes/Images/camera.png'),
    Auction: require('../asstes/Images/Auction.png'),
    BOTTOM_BG: require('../asstes/Images/bottombg.png'),
    Dashboard: require('../asstes/Images/Dashboard.png'),
    Heart: require('../asstes/Images/heart.png'),
    LOVE: require('../asstes/Images/love.png'),
    HOME: require('../asstes/Images/home.png'),
    FLOAT: require('../asstes/Images/float.png'),
    B: require('../asstes/Images/b.png'),
    CLOCK: require('../asstes/Images/clock.png'),
    HOME_HEADER: require('../asstes/Images/header.png'),
    BELL: require('../asstes/Images/bell.png'),
    SEARCH: require('../asstes/Images/search.png'),
    APPLE: require('../asstes/Images/apple.png'),
    CAMERA_SHOT: require('../asstes/Images/camerashot.png'),
    VIDEO: require('../asstes/Images/video.png'),
    HAIER: require('../asstes/Images/haier.png'),
    MOBILE: require('../asstes/Images/mobile.png'),
    I: require('../asstes/Images/iicon.png'),
    BACKARROWE: require('../asstes/Images/back.png'),
    MOBILEDETAIL: require('../asstes/Images/mobiledetail.png'),
    FILTER: require('../asstes/Images/filter.png'),
    SHARE: require('../asstes/Images/share.png'),
    WHITE_I: require('../asstes/Images/whitei.png'),
    BLACK_HEART: require('../asstes/Images/blackheart.png'),
    CHECK: require('../asstes/Images/check.png'),
    RIGHT: require('../asstes/Images/right.png'),
    PLUS: require('../asstes/Images/plus.png'),
    WALLET: require('../asstes/Images/wallet.png'),
    CHECK_CIRCLE: require('../asstes/Images/checkcircle.png'),
    UN_CHECK_CIRCLE: require('../asstes/Images/uncheckcircle.png'),
    VISA: require('../asstes/Images/visa.png'),
    PAYPAL: require('../asstes/Images/paypal.png'),
    AFFIRM: require('../asstes/Images/affirm.png'),
    APPLE_ICON: require('../asstes/Images/apple.png'),
    MASTER_CARD: require('../asstes/Images/master.png'),
    PAYMENT_BG: require('../asstes/Images/paymentbg.png'),
    SUCCES: require('../asstes/Images/succes.png'),
    APPLE_WHITE: require('../asstes/Images/applewhite.png'),





}