export const All_Text = {
    Login_or_Register: 'Login or Register',
    PHONE_NUMBER: 'Enter your phone number\nto continue',
    Send_OTP: 'Send OTP',
    By_signing_up: 'By signing up you are agree to our ',
    Terms_Conditions: 'Terms & Conditions',
    And: ' and',
    Privacy_Policy: ' Privacy Policy',
    OTP_Verification: 'OTP Verification',
    ENTER_THE_CODE: 'Enter the code we sent to the number ending ****7502',
    DONT_RECIVE_CODE: `Didn't receive code?`,
    Resend: ` Resend`,
    Verify: 'Verify',
    Profile_Setup:'Profile Setup',
    Dont_Worry:`Don't worry, your personal data is completely private`,
    Name:'Name',
    Username :'Username',
    Email:'Email',
    Continue:'Continue',
    Number:`Phone Number`,
    HOME:'Home',
    Auction:'Auction',
    Favorites:'Favorites',
    Dashboard:'Dashboard',
    Hello:'Hello!',
    John_William:'John William',
    Search_here:'Search here',
    Shop_by_Brand:'Shop by Brand',
    Shop_by_Category:'Shop by Category',
    Bid_Now:'Bid Now',
    Cameras:'Cameras',
    See_All:'See All',
    Featured_Items:"Featured Items",
    Xiaomi:'Xiaomi',
    Xiaomi_Brand:'Xiaomi 14 / 14 Pro',
    DOLOR:'$400.00',
    DOLLOR_CUT:'$800.00',
    Unit:"Unit",
    XIAOMI_NAME:'Xiaomi 14 Ultra! Prepare to embark on a journey where innovation',
    Please_Add_Your_Payment :'Please Add Your Payment Details',
    For_placing:'For placing a bid please add your\n payment details',
    Card_Number:'Card Number',
    Enter_card_number:'Enter card number',
    Expiry_Date:"Expiry Date",
    Enter_expiry_date:'Enter expiry date',
    CVV:'CVV',
    Enter_CVV_number:'Enter CVV number',
    Card_Holder_Name:'Card Holder Name',
    Enter_card_holder_name:'Enter card holder name',
    Save_Card_Details:'Save Card  Details',
    GRANTS:'Grants an all-access pass to the bidding arena,\n with no limits on how many bids you can place',
    PERFECT:'Perfect for the serious bidder, it brings the\n thrill of making endless bids in real-time\n auctions',
    Add_New_Card:'Add New Card',
    All_Cards:'All Cards',
    Payment_Added_Successfully :'Payment Added Successfully '
}
