name: Build and Upload to TestFlight

on:
  workflow_dispatch:
  
jobs:
  build_and_upload:
    name: Build and upload to TestFlight
    runs-on: macos-latest  # Corrected attribute for macOS build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Cache CocoaPods
        uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust node version as per your project's requirements
      
      - name: Install dependencies
        run: |
          npm install
          gem install bundler
          bundle install

      - name: Set up environment
        env:
          APP_SPECIFIC_PASS: ${{ secrets.APP_SPECIFIC_PASS }}
          DECRYPTION_PASS_CERTIFICATE: ${{ secrets.DECRYPTION_PASS_CERTIFICATE }}
          DECRYPTION_PASS_PROFILE: ${{ secrets.DECRYPTION_PASS_PROFILE }}
          KEYCHAIN_EXPORT: ${{ secrets.KEYCHAIN_EXPORT }}
        run: |
          # Install project dependencies
          cd ios
          pod install
          cd ..
          # Add a distribution certificate to the keychain
          chmod +x ./.github/scripts/set_certificates.sh
          ./.github/scripts/set_certificates.sh

      - name: Build iOS App
        run: |
          # Run Fastlane and capture the output
          fastlane_output=$(fastlane development)
          echo "Fastlane Output:"
          echo "$fastlane_output"

          # Find the IPA file path in the output
          ipa_path=$(echo "$fastlane_output" | grep -o "Generated IPA path: .*" | cut -d ' ' -f 4-)
          echo "IPA file path: $ipa_path"

          # Set the IPA_PATH variable for subsequent steps
          echo "##vso[task.setvariable variable=IPA_PATH;]$ipa_path"

      - name: Upload to TestFlight
        run: |
          cd upload
          fastlane development
